spring:
  datasource:
    url: jdbc:h2:mem:sco
    driver-class-name: org.h2.Driver
    username: dbs
    password:
  h2:
    console:
      enabled: true
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true